### ISSUE TITLE
Argentina(AR) number formatting and validation errors

### ISSUE THREAD

**Issue by byungjikroh** [socialpaymentsbv/ex_phone_number#24] opened 2018-09-19 06:31 UTC
I've been using this library for a few years, but there are errors to format and validate Argentina numbers. 

A formatted national number of AR by the library is invalid and not formatted again properly.
The only difference of result is 'italian_leading_zero: true' at second formatting.

Could you check it? Thanks. :)

**Initial formatting**
```
iex> {:ok, phone_number} = ExPhoneNumber.parse("+54 114321-1200", "AR")
{:ok,
 %ExPhoneNumber.Model.PhoneNumber{
   country_code: 54,
   country_code_source: nil,
   extension: nil,
   italian_leading_zero: nil,
   national_number: 1143211200,
   number_of_leading_zeros: nil,
   preferred_domestic_carrier_code: nil,
   raw_input: nil
 }}

iex> ExPhoneNumber.format(phone_number, :national)
"011 4321-1200"

iex> ExPhoneNumber.is_valid_number?(phone_number)
true
```

**Second formatting**
```
iex> {:ok, phone_number} = ExPhoneNumber.parse("011 4321-1200", "AR")
{:ok,
 %ExPhoneNumber.Model.PhoneNumber{
   country_code: 54,
   country_code_source: nil,
   extension: nil,
   italian_leading_zero: true,
   national_number: 1143211200,
   number_of_leading_zeros: nil,
   preferred_domestic_carrier_code: nil,
   raw_input: nil
 }}

iex> ExPhoneNumber.format(phone_number, :national)
"01143211200"

iex> ExPhoneNumber.is_valid_number?(phone_number)
false

```

**Comment by byungjikroh** [comment] 2018-09-19 16:17
Google's libphonenumber library has no problem. 

Java version(linked on libphonenumber) result with same AR phone number above.
https://libphonenumber.appspot.com/phonenumberparser?number=011%204321-1200&country=AR

It returns 'italian_leading_zero' false but ex_phone_number does not (It returns true). 
I suppose this difference might cause an error. 

I have been using Ruby version (https://github.com/daddyz/phonelib) and Golang version (https://github.com/nyaruka/phonenumbers) but they works fine with AR phone numbers.

**Comment by szymon-jez** [comment] 2018-09-20 07:34
Thanks for your research.
Does upgrading PhoneNumberMetadata.xml (replacing the current one with the one I linked from Google) fix the issues you are having? Could you then create a PR that would include tests that show if your issues is present and upgrade that XML file?

**Comment by byungjikroh** [comment] 2018-09-20 08:50
I'm not sure I've done right but replacing current PhoneNumberMetadata.xml and PhoneNumberMetadataForTesting with Google's makes validation worse. 

AR phone numbers are still returned invalid and other countries either.

```
iex(1)> {:ok, phone_number} = ExPhoneNumber.parse("+54 114321-1200", "AR")
{:ok,
 %ExPhoneNumber.Model.PhoneNumber{
   country_code: 54,
   country_code_source: nil,
   extension: nil,
   italian_leading_zero: nil,
   national_number: 1143211200,
   number_of_leading_zeros: nil,
   preferred_domestic_carrier_code: nil,
   raw_input: nil
 }}
iex(2)> ExPhoneNumber.format(phone_number, :national)
"011 4321-1200"
iex(3)> ExPhoneNumber.is_valid_number?(phone_number)
false

iex(4)> {:ok, phone_number} = ExPhoneNumber.parse("011 4321-1200", "AR")
{:ok,
 %ExPhoneNumber.Model.PhoneNumber{
   country_code: 54,
   country_code_source: nil,
   extension: nil,
   italian_leading_zero: true,
   national_number: 1143211200,
   number_of_leading_zeros: nil,
   preferred_domestic_carrier_code: nil,
   raw_input: nil
 }}
iex(5)> ExPhoneNumber.format(phone_number, :national)
"01143211200"
iex(6)> ExPhoneNumber.is_valid_number?(phone_number)
false

iex(7)> {:ok, phone_number} = ExPhoneNumber.parse("555-555-5555", "US")
{:ok,
 %ExPhoneNumber.Model.PhoneNumber{
   country_code: 1,
   country_code_source: nil,
   extension: nil,
   italian_leading_zero: nil,
   national_number: 5555555555,
   number_of_leading_zeros: nil,
   preferred_domestic_carrier_code: nil,
   raw_input: nil
 }}
iex(8)> ExPhoneNumber.format(phone_number, :national)
"(555) 555-5555"
iex(9)> ExPhoneNumber.is_valid_number?(phone_number)
false
```

Moreover, there is an exception error on a UK phone number like below. 
The number is 01131688131 and it is a valid number. 
```
 an exception was raised:
    ** (FunctionClauseError) no function clause matching in Regex.run/3
        (elixir) lib/regex.ex:279: Regex.run(nil, "1131688131", [return: :index])
        (ex_phone_number) lib/ex_phone_number/validation.ex:119: ExPhoneNumber.Validation.test_number_length_against_pattern/2
        (ex_phone_number) lib/ex_phone_number/validation.ex:87: ExPhoneNumber.Validation.is_shorter_than_possible_normal_number?/2
        (ex_phone_number) lib/ex_phone_number/parsing.ex:117: ExPhoneNumber.Parsing.parse_helper/4
...
```

I think that replacing raw Metadata can't solve the problem. It might require some refactoring work.

**Comment by szymon-jez** [comment] 2018-09-20 08:58
> I think that replacing raw Metadata can't solve the problem. 

Yes, the data you provided above proves this.

> It might require some refactoring work.

I think you mean re-engineering or fixing.
I also think that you seem well versed in this topic (you know how to test those matters) and because of this I think you are capable of doing the fix. Is that possible that you would find the time to design and implement a solution? I will be happy to review your work and help out.

**Comment by szymon-jez** [comment] 2019-02-04 09:20
In https://github.com/socialpaymentsbv/ex_phone_number/pull/27 the XML Metadata was updated. Could you check if this resolves your issues?

**Comment by szymon-jez** [comment] 2019-02-04 10:08
And from your first post:

```elixir
iex(14)> ExPhoneNumber.parse("+54 114321-1200", "AR")
{:ok,
 %ExPhoneNumber.Model.PhoneNumber{
   country_code: 54,
   country_code_source: nil,
   extension: nil,
   italian_leading_zero: nil,
   national_number: 1143211200,
   number_of_leading_zeros: nil,
   preferred_domestic_carrier_code: nil,
   raw_input: nil
 }}
iex(15)>  ExPhoneNumber.format(phone_number, :national)
"0113 168 8131"
iex(16)> ExPhoneNumber.is_valid_number?(phone_number)
true
iex(17)>  ExPhoneNumber.parse("011 4321-1200", "AR")
{:ok,
 %ExPhoneNumber.Model.PhoneNumber{
   country_code: 54,
   country_code_source: nil,
   extension: nil,
   italian_leading_zero: true,
   national_number: 1143211200,
   number_of_leading_zeros: nil,
   preferred_domestic_carrier_code: nil,
   raw_input: nil
 }}
iex(18)> ExPhoneNumber.format(phone_number, :national)
"0113 168 8131"
iex(19)> ExPhoneNumber.is_valid_number?(phone_number)
true
``

**Comment by byungjikroh** [comment] 2019-02-07 09:00
> And from your first post:
> 
> ```elixir
> iex(14)> ExPhoneNumber.parse("+54 114321-1200", "AR")
> {:ok,
>  %ExPhoneNumber.Model.PhoneNumber{
>    country_code: 54,
>    country_code_source: nil,
>    extension: nil,
>    italian_leading_zero: nil,
>    national_number: 1143211200,
>    number_of_leading_zeros: nil,
>    preferred_domestic_carrier_code: nil,
>    raw_input: nil
>  }}
> iex(15)>  ExPhoneNumber.format(phone_number, :national)
> "0113 168 8131"
> iex(16)> ExPhoneNumber.is_valid_number?(phone_number)
> true
> iex(17)>  ExPhoneNumber.parse("011 4321-1200", "AR")
> {:ok,
>  %ExPhoneNumber.Model.PhoneNumber{
>    country_code: 54,
>    country_code_source: nil,
>    extension: nil,
>    italian_leading_zero: true,
>    national_number: 1143211200,
>    number_of_leading_zeros: nil,
>    preferred_domestic_carrier_code: nil,
>    raw_input: nil
>  }}
> iex(18)> ExPhoneNumber.format(phone_number, :national)
> "0113 168 8131"
> iex(19)> ExPhoneNumber.is_valid_number?(phone_number)
> true
> ``
> ```

**Comment by szymon-jez** [comment] 2019-02-07 10:00
Thanks for checking. I now have also read it all and I confirm that we have still this bug here.

> I thank you for suggesting but refactoring all country's code is out of my capability.

As we have recently updated the metadata (XML).

> I'll try to fix AR phone numbers errors first and request to pull later. :)

Now it should be much easier for to try fixing the part of the code that is causing this issues.

**Comment by byungjikroh** [comment] 2019-02-07 11:25
Okay, I'll try checking AR phone number format code. 
Thanks for updating metadata (XML). 😃

**Comment by ideaMarcos** [comment] 2019-06-17 21:24
Was trying to see what was going on here so I was able to reproduce the original issue with iex. Then I added a test to `validation_test.exs` to investigate

```
    context "test AR number" do
      it "returns true" do
        assert {:ok, phone_number} =
                 ExPhoneNumber.parse("011 4321-1200", "AR")
                 |> IO.inspect(label: "phone_number")

        assert is_valid_number?(phone_number)
               |> IO.inspect(label: "is_valid_number?")
      end
    end
```

This test passes which is weird. I get a different result from parse() than in iex

```
phone_number: {:ok,
 %ExPhoneNumber.Model.PhoneNumber{
   country_code: 54,
   country_code_source: nil,
   extension: nil,
   italian_leading_zero: nil,
   national_number: 1143211200,
   number_of_leading_zeros: nil,
   preferred_domestic_carrier_code: nil,
   raw_input: nil
 }}
is_valid_number?: true
```

Only difference is `italian_leading_zero: nil`. Not sure if I'm doing something wrong here.

**Comment by szymon-jez** [comment] 2022-04-29 07:42
Closing for now as #43 may fix those issues. If after doing #43 those issues will still prevail we can reopen.

**Closed by szymon-jez** 2022-04-29 07:42 UTC
Labels: bug
